#!/bin/bash
# Creates Odoo folder structure with given module name

if [ $1 = $1 ]; then # TODO: module name validation
    
    mkdir $1
    cd $1
    # initialize folder structure
    mkdir controllers data models security static views

    # create subfolder structure for static
    cd static
    mkdir img lib src
    cd src
    mkdir js css less xml
    cd ../..
    
    # create init files and openerp manifest
    touch __init__.py
    echo import_models > __init__.py
    
    touch models/__init__.py
    touch controllers/__init__.py

    touch __openerp__.py
    # TODO: create default manifest structure

    # create .gitignore
    touch .gitignore

    echo Created new module $1
else
    echo Invalid module name $1
fi
