#!/bin/bash
# Creates Odoo folder structure with given module name

if [ $1 = $1 ]; then # TODO: module name validation
    echo Creating module with name $1 in $PWD
    
    mkdir $1
    cd $1
    # initialize folder structure
    mkdir controllers data models security static views

    # create subfolder structure for static
    cd static
    mkdir img lib src
    cd src
    mkdir js css less xml
    cd ../..
    

    # create init and openerp manifest
    touch __init__.py
    echo import_models > __init__.py
    
    touch models/__init__.py

    touch __openerp__.py
    # TODO: create default manifest structure

else
    echo Invalid module name $1
fi
